# yaml-language-server: $schema=https://schemastore.org/github-workflow
jobs:
  check:
    runs-on: windows-latest
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@main
      - uses: xmake-io/github-action-setup-xmake@master
        with:
          actions-cache-folder: .xmake
      - uses: ZhongRuoyu/setup-llvm@main
        with:
          llvm-version: 21
      - run: xmake format:check
      - run: winget add --accept-package-agreements --accept-source-agreements feraxhp.cim Microsoft.WindowsSDK.10.0.26100
      - uses: bwoodsend/setup-winlibs-action@v1
        with:
          tag: 15.2.0posix-13.0.0-ucrt-r5
      - run: xmake check syntax
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
