# yaml-language-server: $schema=https://schemastore.org/github-workflow
jobs:
  check:
    runs-on: windows-latest
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@main
      - uses: xmake-io/github-action-setup-xmake@master
        with:
          actions-cache-folder: ${{ runner.temp }}/xmake
      - run: xmake format:check
      - uses: qwertycxz/setup-cim@master
      - run: xmake check syntax
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
permissions:
  contents: read
