# yaml-language-server: $schema=https://schemastore.org/github-workflow
jobs:
  check:
    runs-on: windows-latest
    steps:
      - run: '$env:PATH'
      - run: clang-format --version
      - run: ls 'C:\Program Files (x86)\Windows Kits\10\Include'
on:
  push:
    branches: [test-cicd]
