# yaml-language-server: $schema=https://schemastore.org/github-workflow
jobs:
  check:
    runs-on: windows-latest
    steps:
      - run: '$env:PATH'
      - run: gcc -v
on:
  push:
    branches: [test-cicd]
